### PR TITLE
Improve Development Environment

### PR DESCRIPTION
**Pull request by ligthyear**
Improve the vagrant setup:

 - Replace the copy of the start.sh script with a link to the actual files
 - switching to tuned NFS for synced folders improves webpack watch performance _a lot_
 - prettier start message

### CODE REVIEW

**Comment by ligthyear** [comment]
Okay. updated, ready for review again @ezmiller

**Comment by ligthyear** [comment]
Performance on a "watch: true" (so highest ping it could do) with the NFS setup on my system now:

screen shot 2015-12-03 at 16 40 50

And vbox is at about 50% CPU (that's fine!) on my mac, too.

**Comment by ligthyear** [comment]
This is what the awesome new message looks like now.

screen shot 2015-12-03 at 17 08 14

**Comment by ezmiller** [comment]
Very nice. We might want to gender neutralize the last, very charming,
greeting. "Champ" is usually what older men to say to younger men/boys.

**Comment by ligthyear** [comment]
Didn't know it had that sound - what would you propose?

**Comment by ezmiller** [comment]
Nothing is coming to mind. I think taking it out is also okay. The greeting is still nice. Funny thing about warm greetings, that they often have a gendered dimension.

**Comment by ezmiller** [comment]
Looks good. Great about the nfs performance spike. @homu r+

**Pull request merged**
