### PR TITLE
Fix Admin access problem:

### PR DESCRIPTION
**Pull request by ligthyear**
Some of our models don't have `__mapper_args__` (specifically the
User model) which our query builder assumes to be there. Resulting
in an ugly 500/traceback when trying to access.

This change fixes this by a more error-resistant lookup procedure.

### CODE REVIEW

**Comment by ligthyear** [comment]
@ezmiller ready for review + merge, when you are

**Comment by ezmiller** [comment]
@homu r+

**Comment by ezmiller** [comment]
@homu retry

**Comment by ligthyear** [comment]
@homu r=ezmiller

**Comment by ezmiller** [comment]
@homu r+

**Comment by ligthyear** [comment]
@homu r=ezmiller

**Comment by ligthyear** [comment]
@homu retry

**Comment by ligthyear** [comment]
@homu r=ezmiller

**Comment by ligthyear** [comment]
@homu r+

**Comment by ligthyear** [comment]
@homu retry

**Comment by ligthyear** [comment]
closing for homu

**Pull request closed without merging**
