### PR TITLE
Upgrade to latest Prosemirror 3.0

### LINKED ISSUE #69: Update to Prose Mirror 0.2.0
With the [first releases of ProseMirror](https://discuss.prosemirror.net/t/release-0-2-0/154), we should probably update to that one instead of sticking to an out of date git-commit. Although we are still prior to 1.0 with prose mirror, I feel confident now that we want start building our case on top of it.

In order to update we need:

 - [] switch to [npm-packages for prose mirror](https://github.com/beavyHQ/beavy/blob/master/package.json#L44) (rather than raw repo)
  - [ ] which potentially means we need to [update the way it is included right now](https://github.com/beavyHQ/beavy/blob/master/.infrastructure/webpack/make-webpack-config.js#L182-L187)
 - [ ] update [prosemirror-react and make sure it still works](https://github.com/beavyHQ/beavy/blob/master/package.json#L48)
 - [ ] update our code to [correctly interact with prose mirror](https://github.com/beavyHQ/beavy/blob/master/beavy/jsbeavy/components/Editor.jsx)

### PR DESCRIPTION
**Pull request by ligthyear**
Fixes #69 and hopefully also the build.

### CODE REVIEW

**Comment by ligthyear** [comment]
@ezmiller this fixes the build and once merged should also make your PR pass again (you need to tell homu about it). If you could review...

**Comment by ezmiller** [comment]
Looks good to me. @homu r+

**Comment by ezmiller** [comment]
@ligthyear looks like a test failed here.

**Comment by ligthyear** [comment]
Bad Timing: Looks like soundcloud changed some meta data while I pushed... pfft.

@homu +retry

**Comment by ligthyear** [comment]
@homu retry

**Comment by ezmiller** [comment]
@home retry

**Comment by ezmiller** [comment]
@homu retry

**Comment by ezmiller** [comment]
@ligthyear is this stuck? seems like the homo status is not reporting.

**Comment by ezmiller** [comment]
@homu r+

**Pull request merged**
