### PR TITLE
Adds tmux options to start.sh to allow scrolling via mouse

### PR DESCRIPTION
**Pull request by ligthyear**
These few options added to the start.sh configure the tmux
session with mouse scrolling enabled. If you have a terminal
set up for scrolling with mouse (like iTerm2 per default)
you can now easily search back the history and select panels
by scrolling and clicking – very useful for debugging ;) .

### CODE REVIEW

**Comment by ezmiller** [comment]
Nice, seems ready to be merged no?

**Comment by ezmiller** [comment]
@ligthyear funny this isn't merge-able because it's asking us to merge the latest changes on master first. There was a button for this on the addhomeview branch before, but it's not showing up here. I also tried to pull the branch down locally and merge from there, but I can't seem to locate the branch.

**Comment by ligthyear** [comment]
That is probably because this branch is on a repo, you can't access – on my fork. I have the button and will do it. But that is an important thing to keep in mind, as it means you can't just merge a bunch of (reviewed) PRs, if they come from other peoples repos ... HMmmm...

**Comment by ezmiller** [comment]
Okay.

**Pull request merged**
